Module opentelemetry/instrumentation-grpc required (#2283)
This is a minor README.md update. It looks like we also need module @opentelemetry/instrumentation-grpc, otherwise we are getting module not found error.
% node -r ./tracing.js app.js
internal/modules/cjs/loader.js:888
  throw err;
  ^

Error: Cannot find module '@opentelemetry/instrumentation-grpc'
Require stack:
- /tracing.js
- internal/preload
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
    at Function.Module._load (internal/modules/cjs/loader.js:730:27)
    at Module.require (internal/modules/cjs/loader.js:957:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/ps105769/POC/open_tel/tracing.js:7:33)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Module.require (internal/modules/cjs/loader.js:957:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/tracing.js', 'internal/preload' ]
}